backend:
  name: github
  repo: oscarmoscaoli/marciorubia
  branch: main

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Postagens do Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de Publicação", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "select", options: ["Previdenciário", "Trabalhista", "Dicas"]}
      - {label: "Resumo", name: "description", widget: "text"}
      - {label: "Corpo do Artigo", name: "body", widget: "markdown"}
